[package]
name = "homaya-algorithms"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "HOMAYA homaya-algorithms"

[dependencies]
homaya-core = { path = "../homaya-core" }
