[package]
name = "homaya-backends"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "HOMAYA homaya-backends"

[dependencies]
homaya-core = { path = "../homaya-core" }
