[package]
name = "homaya-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "HOMAYA homaya-runtime"

[dependencies]
homaya-core = { path = "../homaya-core" }
